# Generated by Django 4.1.12 on 2023-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(1, 'Men'), (2, 'Women'), (3, 'Diffrent')])),
                ('date_of_birth', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
