# Generated by Django 4.1.12 on 2023-11-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcenaKebaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.IntegerField(default=0, help_text='Ocena miesa w skali od 1 do 10')),
                ('sauce', models.IntegerField(default=0, help_text='Ocena sosu w skali od 1 do 10')),
                ('vegetables', models.IntegerField(default=0, help_text='Ocena warzyw w skali od 1 do 10')),
                ('additions', models.IntegerField(default=0, help_text='Ocena dodatkow w skali od 1 do 10')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('typeRestaurant', models.IntegerField(choices=[(1, 'Kebab'), (2, 'Zapiekanka')])),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
