# Generated by Django 4.1.12 on 2023-11-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_ocenakebaba_restaurant_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingKebaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat', models.IntegerField(default=0, help_text='Ocena miesa w skali od 1 do 10')),
                ('sauce', models.IntegerField(default=0, help_text='Ocena sosu w skali od 1 do 10')),
                ('vegetables', models.IntegerField(default=0, help_text='Ocena warzyw w skali od 1 do 10')),
                ('additions', models.IntegerField(default=0, help_text='Ocena dodatkow w skali od 1 do 10')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='OcenaKebaba',
        ),
    ]
