# Generated by Django 4.1.12 on 2023-11-24 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_ratingkebaba_additions_alter_ratingkebaba_meat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingkebaba',
            name='final_grade',
            field=models.FloatField(default=0.0, help_text='Ostateczna ocena', validators=[django.core.validators.validate_integer]),
        ),
        migrations.CreateModel(
            name='RatingZapiekanka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread', models.IntegerField(default=0, help_text='Ocena pieczywa w skali od 1 do 10', validators=[polls.models.validate_rating])),
                ('cheese', models.IntegerField(default=0, help_text='Ocena sera w skali od 1 do 10', validators=[polls.models.validate_rating])),
                ('sauce', models.IntegerField(default=0, help_text='Ocena sosu w skali od 1 do 10', validators=[polls.models.validate_rating])),
                ('additions', models.IntegerField(default=0, help_text='Ocena dodatkow w skali od 1 do 10', validators=[polls.models.validate_rating])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.person')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.restaurant')),
            ],
        ),
    ]
